#yml is space sensitive 
spring:
  profiles:
    active: dog,FRN,qa

henrietha:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlURL



#    content of application.properties file that is being converted to .yml file
#    spring.profiles.active=dog,FRN,qa
#
#    #HENRIETHA.USERNAME= UserFromEnvVar!
#    #--henrietha.password=PwdFromCmdLine --henrietha.username=UserFromCmdLine
#    henrietha.username=henrietha
#    henrietha.password=12345
#    henrietha.jdbcurl=someUrlforDB
