#yml files are extremely space sensitive
spring:
  profiles:
    active:
      - dog
      - FRN
      - prod

henrietha:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlURL


#The --- signifies a yml file separator giving birtn to a new yml file
---
spring:
  profiles: prod

henrietha:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdURL




#    content of application.properties file that is being converted to .yml file
#    spring.profiles.active=dog,FRN,qa
#
#    #HENRIETHA.USERNAME= UserFromEnvVar!
#    #--henrietha.password=PwdFromCmdLine --henrietha.username=UserFromCmdLine
#    henrietha.username=henrietha
#    henrietha.password=12345
#    henrietha.jdbcurl=someUrlforDB
